payment model, invoice model, registration queryset
blueridger/HiFi-Registration pull request #18
Opened 2020-06-17 19:38 UTC by connorfrendt

2020-06-19 02:10 UTC, blueridger requested changes
1 change needed. Also it would be good to add to the PR description that the tests pass (if they do)

2020-06-19 02:10 UTC, blueridger commented on hifireg/registration/models/payments.py
> +class Payments(models.Model):
Need to delete this class, you already have "Payment" class. looks like a mishap from the git stuff we did.

2020-06-21 22:35 UTC, connorfrendt commented
Deleted the payments.py file (as there is already a payment.py file).
All of my tests pass as well!

2020-06-21 22:43 UTC, connorfrendt commented
Deleted payments.py as requested, and all of my tests pass as well!

2020-06-21 22:46 UTC, blueridger approved these changes

2020-06-23 03:37 UTC, merged