Task 4 of 5 | Payment & Stripe | Record Payment
blueridger/HiFi-Registration pull request #23
Opened 2020-06-29 17:32 UTC by tiftaylor

Records Payment in Database & ensures Session ID's are Unique so there are no duplicates in the database

DONE - Add Stripe session ID to Payment model
DONE - Change mock code in NewCheckoutView to use self.order.invoice_set.get(pay_at_checkout=True)
DONE - Update the PaymentConfirmationView with code that populates the Payment model
DONE - Made sure each session ID is unique incase they refresh the confirmation page, more can't be added to the table

**Checkout Session NOW pulls CORRECT Total:** 
<img width="983" alt="Screen Shot 2020-06-29 at 9 58 26 AM" src="https://user-images.githubusercontent.com/36306993/86037041-a5519480-b9f3-11ea-8614-8608431bd3a8.png">

**Payment's are stored with Unique Session ID**
<img width="694" alt="Screen Shot 2020-06-29 at 10 26 01 AM" src="https://user-images.githubusercontent.com/36306993/86037160-c9ad7100-b9f3-11ea-9e7e-645103f1c99e.png">

2020-06-29 18:46 UTC, blueridger requested changes

2020-06-29 18:46 UTC, blueridger commented on hifireg/registration/views/registration.py
> +            payment = Payment.objects.create(amount=total_amount, registration=self.registration, stripe_session_id=session_id)
Whatever happened to the requirement to set order.session to None? I don't see it in any of the asana tasks anymore, but that is still needed to set the order as complete. I would recommend adding the order.pk to the request.session object in the NewCheckoutView and then grabbing the order in this view that way.

https://docs.djangoproject.com/en/3.0/topics/http/sessions/#session-object-guidelines

2020-06-29 18:46 UTC, blueridger commented on hifireg/registration/views/registration.py
> +class PaymentConfirmationView(RegistrationRequiredMixin, FunctionBasedView, View):
For future reference, a more likely industry pattern would be to have a PaymentRedirectView that Stripe redirects to, that handles the payment record creation and order finalization and then redirects to the PaymentConfirmationView, which would be a read-only view. I think this is fine for now, though.

2020-06-29 18:46 UTC, blueridger commented on hifireg/registration/models/payment.py
> +   stripe_session_id = models.TextField(verbose_name='Stripe Session ID', null=True, blank=True, unique=True)
null and blank should probably be false (default)

2020-06-30 20:41 UTC, tiftaylor commented on hifireg/registration/views/registration.py
> +            payment = Payment.objects.create(amount=total_amount, registration=self.registration, stripe_session_id=session_id)
@blueridger 
I will set the order.session to None like you mention on the first line - but, why do we need to add the order.pk to the session - it looks like the self.order is already associated with the current session.

2020-06-30 20:56 UTC, tiftaylor commented on hifireg/registration/models/payment.py
> +   stripe_session_id = models.TextField(verbose_name='Stripe Session ID', null=True, blank=True, unique=True)
Ok, I will set these to False. Please Note, if anyone on the team has lines of data in their payment table, a migrate error will likely show up.

2020-06-30 23:22 UTC, blueridger commented on hifireg/registration/views/registration.py
> +            payment = Payment.objects.create(amount=total_amount, registration=self.registration, stripe_session_id=session_id)
It is now that you've added the OrderRequiredMixin. However this means that the PaymentConfirmation page cannot be refreshed anymore, because that mixin will redirect to the beginning of registration. I'm cool with this page not being refresh-safe, but it leaves me with these notes:
- we should make a custom mixin that redirects to the landing page instead of the beginning of registration.
- I'm also curious if you have tested what happens if you forceful browse to this page during registration without a stripe id in the url parameters
- since the page is no longer refresh-safe, the try/except isn't really the right structure. a custom mixin that does the pre-work and conditions checking would probably be better.

This works though, and I would love to have this in develop sooner than later. We can make follow up refactors to answer these points later.

2020-06-30 23:22 UTC, blueridger approved these changes
Approved with comments.

2020-07-01 00:46 UTC, merged