Post order Payment page for all other invoices
blueridger/HiFi-Registration pull request #25
Opened 2020-07-05 21:16 UTC by tiftaylor

A) New page accessible from the landing page. (30 min)
 ✔️DONE -- Button on Landing Page (html & on IndexView)
 ✔️DONE -- URL in urls.py
 ✔️DONE -- Class View added to other views on views/registration.py
 ✔️DONE -- create HTML template

B) Should have a list of unpaid invoices with a check box, amount and due date. The next due invoice should be checked by default. (2 hour)
✔️DONE -- Get the InvoicesView to load invoices from DB
✔️DONE -- Sort invoices by ascending due date in the InvoicesView
✔️DONE -- Add context to the empty dictionary in InvoicesView
✔️DONE -- Add Checkboxes to invoices.html
✔️DONE -- Add invoice rows to html 
✔️DONE -- Top invoice input box should be checked
✔️DONE -- used Filter special sauce for cent conversion to show dollar in the invoices.html

C) Somehow, we need to enforce that invoices are paid in order. (can only pay last if also paying first) Not sure what the UX for this should be. (1 hour)
✔️DONE -- I can check/uncheck any box. When I check a box, it also checks all previous boxes. When I uncheck a box, it also unchecks all following boxes.
✔️DONE -- if no boxes are checked, disable pay button (fail safe for ensure the first invoice is checked via all other logic)

D) Should have a Select/Unselect All checkbox above the list. (20 min)
✔️DONE -- Add "Select All" input, innerHMTL toggle to "Unselect All" when box is checked (create invoices.js)

E) At the top, should have a Make a Payment section with an autocalculated Amount (sum of checked invoices) and a Checkout button that's Stripe integrated. (3 hours)
✔️DONE -- Bordered div that contains: Title, Total Amount (selected), and Pay Invoice(s) Button
✔️DONE -- Write math on NEW .js file (or the one you created earlier in this task) to total checked invoices
✔️DONE-- JS code for Pay Invoice(s) Button
✔️DONE -- For button create NEW view (and New URL for it) (but duplicated) Stripe Integration - in views/registration.py create new class view PayInvoicesView (copy other stripe api code from NewCheckoutSessionView, the 1 product inline will be the JavaScript invoices sum-total

F) After checkout, redirect back to this page, with a success banner that displays the amount paid. (Suggested: use a url param for the amount to optionally display the banner if the param is present) (45 minutes)
✔️DONE -- Stripe redirects to success_url
✔️DONE -- Write (again) new code to capture stripe session ID tagged onto each payment id that was paid
✔️DONE -- Redirect to THIS payment page providing URL with added param indicating payment was successful 
✔️DONE -- Create banner display w/{{success - amount paid}} on the invoices.html 

G) ✔️DONE -- Use basic bulma CSS to make the html page look presentable (30 min DO LAST)

**Various Screenshots showing tasks:** 
<img width="1075" alt="Screen Shot 2020-07-05 at 2 00 34 PM" src="https://user-images.githubusercontent.com/36306993/86542351-ee10be00-bec9-11ea-975a-dda0c0a04f85.png">

<img width="382" alt="Screen Shot 2020-07-05 at 2 01 18 PM" src="https://user-images.githubusercontent.com/36306993/86542355-f7018f80-bec9-11ea-95d4-7ddfee935c67.png">

<img width="1054" alt="Screen Shot 2020-07-05 at 2 03 34 PM" src="https://user-images.githubusercontent.com/36306993/86542358-fc5eda00-bec9-11ea-983f-bf28cb7548d7.png">

2020-07-05 23:01 UTC, blueridger requested changes
This is all AMAZING. Just some minor adjustments and learning opportunities I think it'd be good to address now.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    }
FYI this could also be written as
```
for (var i = 1; invoiceCheckboxes[i] !== checkbox; i++) {
    invoiceCheckboxes[i].checked = true;
}
```

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +  function totalPaymentAmount() {
Best practice is to make method names verbs, so in this case using a prefix like get or calculate.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +        amount += parseInt(checkbox.dataset.amount);
awesome use of dataset to keep an integer version of the amount handy and avoid decimal addition!!

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    for (var i = 0; i < checkedCheckboxes.length; i++) {
This would be a good candidate for a forEach loop instead of a for loop. Better practice because it's more readable.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +  // sums up pay amount based on checeked boxes
Typo

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +      if (checkbox.checked) {
This looks like a redundant check, since we should only be iterating checked boxed at this point.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    invoiceCheckboxes[0].checked = true;
This actually feels unintuitive. I like defaulting to the first one checked on page load, but I think this should simply unselect all.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    } else {
We should also set the "Unselect all" button to a "Select all" button here.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    };
This could be simplified to `payInvoicesButton.disabled = amountDue === 0`

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/templates/registration/invoices.html
> +    </tr>
odd indentation

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/views/registration.py
> +                unpaid_invoices.append(invoice)
This could be replaced with:
```
unpaid_invoices = with_is_paid(
            Invoice.objects.filter(
                order__registration__pk=self.registration.pk
            ).order_by('due_date')
        ).filter(is_paid=False)
```
And then you might have to append `.iterator()` too to make it work with the template.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/views/registration.py
> +                return JsonResponse({'error': str(e)})
This looks like a LOT of duplicate code. It'd be cool to create a helper method in the future to avoid duplicate code.

2020-07-05 23:01 UTC, blueridger commented on hifireg/registration/views/registration.py
> +            payment = Payment.objects.create(amount=total_amount, registration=self.registration, stripe_session_id=session_id)
Same here, would be cool to pull duplicate code out into a helper method in the future.

2020-07-09 03:28 UTC, tiftaylor commented on hifireg/registration/templates/registration/invoices.html
> +    </tr>
oops used some tabs. converted all to spaces

2020-07-09 03:38 UTC, blueridger commented on hifireg/registration/static/scripts/invoices.js
> +    }
sorry var i = 0

2020-07-09 04:12 UTC, blueridger approved these changes

2020-07-09 17:14 UTC, merged