Redesign Product Cards
blueridger/HiFi-Registration pull request #29
Opened 2020-08-05 23:17 UTC by tiftaylor

- Redesigned Product Cards to match the Wireframe as closely as possible using as much BULMA as possible
- Needed to manually override a few BULMA defaults in order to match the Wireframe (i.e. Box Shadow, etc)
- NOTE: Currently no Wireframe design for `<p>{{product.part}} of {{product.total_parts}}</p>` so left it alone, maybe you don't really need / want this to avoid UI flow disruption. 

## Images for reference: 
### Wireframe on Left | Current Output on Right

![Screen Shot 2020-08-05 at 4 00 30 PM](https://user-images.githubusercontent.com/36306993/89473087-e184bd00-d736-11ea-9b92-ca766b9e53b9.png)

### Consider removing `<p>{{product.part}} of {{product.total_parts}}</p>` to avoid UI flow disruption

![Screen Shot 2020-08-05 at 4 02 09 PM](https://user-images.githubusercontent.com/36306993/89473099-ea758e80-d736-11ea-99bf-e9567d7e1fda.png)

2020-08-05 23:18 UTC, tiftaylor commented
I figure color correction for when card is selected can be added to some kind of color clean up future task that goes over all reg pages and "cleans" things up like color etc at that time.

2020-08-06 01:56 UTC, blueridger requested changes

2020-08-06 01:56 UTC, blueridger commented on hifireg/registration/templates/registration/product_card.html
>        <p>{{product.part}} of {{product.total_parts}}</p>
Let's keep this and make it is-inline

2020-08-06 01:56 UTC, blueridger commented on hifireg/registration/templates/registration/register_selection.html
> +  <p class="has-text-weight-bold sectionHead is-size-5">1. Let's get started! Select your dances:</p>
This should go outside the above for loop, but doesn't need to be now.

2020-08-06 03:50 UTC, bferg88 commented on hifireg/registration/sass/hifi-styles.scss
> +}
This doesn't appear to look quite right on Safari, but I'm not too concerned about that. 

Also, played with just adding the following CSS and it seems to work in Chrome just fine, but only sorta works in Safari:
```
input[type="checkbox"].big-checkbox
{
	width: 20px;
	height: 20px;
}
```

2020-08-11 04:07 UTC, tiftaylor commented on hifireg/registration/sass/hifi-styles.scss
> +}
I spent a full hour for the 2% of sarafi users to make sure they had a more legit checkmark. Hopefully it's good enough to move forward.

2020-08-11 04:12 UTC, tiftaylor commented
UPDATE for PR Approval: 
- Made product of products inline on cards
- moved the p tag above the for loop noted
- spent way too much time making sure Safari users have a good check mark experience >.>

2020-08-12 00:39 UTC, blueridger approved these changes

2020-08-12 00:40 UTC, merged