Added checkbox toggle when click on product-card
blueridger/HiFi-Registration pull request #3
Opened 2020-05-17 17:19 UTC by Pookitah

- Added a quick gitignore bit for my mac auto making DS_store files
- Made it so product-cards can toggle the checkbox input on single item cards
- Disabled checkbox action when clicking on Details word/Carrot icon near the word
- Added code to check if a checkbox card or multi-select card so the code only runs on check-box cards

2020-05-18 17:32 UTC, blueridger commented on hifireg/registration/static/scripts/ticket_selection.js
> +  //if checkbox is on card, grab the first input element
This comment doesn't really help me understand the purpose of the following block

2020-05-18 17:39 UTC, blueridger commented on hifireg/registration/static/scripts/ticket_selection.js
> +  checkBox.change();
I think these three lines could be replaced with `checkBox.click()` Try it out?

2020-05-18 17:45 UTC, blueridger requested changes
Awesome job overall. A worthy solution. Some minor comments for your consideration.
Also, consider squashing your commits. Check out `git rebase -i` and `git commit --amend`

2020-05-20 00:56 UTC, tiftaylor commented on hifireg/registration/static/scripts/ticket_selection.js
> +  //if checkbox is on card, grab the first input element
Changed wording

2020-05-20 00:56 UTC, tiftaylor commented on hifireg/registration/static/scripts/ticket_selection.js
> +  checkBox.change();
code replaced

2020-05-21 16:47 UTC, blueridger approved these changes

2020-05-22 03:27 UTC, merged