Ash/feature
blueridger/HiFi-Registration pull request #32
Opened 2020-08-21 01:20 UTC by AshlandWest

Changes to Donate page, Nav bar updates, Index page updates, add display_name field.

2020-08-25 04:16 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
> +                    <div class="navbar-item has-dropdown is-hoverable" style="align-self: right;">
Need to send this to the end of the navbar using "navbar-end".

See here and make sure the structure of classes matches:
https://bulma.io/documentation/components/navbar/

2020-08-25 04:16 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
> +                            <a class="navbar-item" href="{% url 'send_email' %}">
This should link to the 'orders' url instead of the 'send_email' url.

2020-08-25 04:16 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
>                              <a class="navbar-item" href="{% url 'send_email' %}">
This should link to the 'view_user' url instead of 'send_email'.

2020-08-25 04:16 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
> -                        <div class="buttons">
Probably should just keep this styling including button as a call to action.
You could probably even bring all of this deleted content back and then put the new stuff in the "if true" part of this condition.

2020-08-26 07:09 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> +                    <div class="navbar-item has-dropdown is-hoverable" style="align-self: right;">
Done

2020-08-26 07:11 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> +                            <a class="navbar-item" href="{% url 'send_email' %}">
Done

2020-08-26 07:12 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
>                              <a class="navbar-item" href="{% url 'send_email' %}">
This has since been deleted entirely

2020-08-26 07:13 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> -                        <div class="buttons">
It is under the profile section now and is included in the if block.

2020-08-27 04:14 UTC, bryant-ferguson requested changes

2020-08-27 04:14 UTC, bryant-ferguson commented on hifireg/registration/templates/registration/index.html
> +    <!-- {% include "utils/button.html" with button=view.invoices_button %} -->
Why is this commented out? I think we still want it, right?

2020-08-27 04:14 UTC, bryant-ferguson commented on hifireg/registration/templates/registration/index.html
> -<div class="field">
Keep this div -- it's necessary for proper spacing from the button. (use suggestion below)

2020-08-27 04:14 UTC, bferg88 commented on hifireg/registration/templates/registration/index.html
> +{% include "utils/form_fields.html" %}
this line doesn't do anything since there is no form on this page -- delete it.
```suggestion
```

2020-08-27 04:14 UTC, bferg88 commented on hifireg/registration/templates/registration/index.html
> +    {% include "utils/button.html" with button=view.register_button %}
Put this class back.
```suggestion
    {% include "utils/button.html" with button=view.register_button class="is-primary" %}
```

2020-08-27 04:14 UTC, bferg88 commented on hifireg/registration/templates/registration/index.html
> +<p>We look forward to dancing with you at this year's HiFi Fusion!</p>
```suggestion
<div class="field">
    <p>Hi, {{ view.request.user.first_name }}!</p>
    <p>We look forward to dancing with you at this year's HiFi Fusion!</p>
</div>
```

2020-08-27 04:14 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
> +                {% endif %}
The if/else/endif should all be aligned and placed such that the resultant code when either body is taken, the resultant code is valid html. You can replace this entire chunk as follows:
```
                <div class="navbar-end">
                    {% if user.is_authenticated %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            <img src="{% static 'assets/profile_icon.png' %}" />
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{% url 'send_email' %}">
                                Account
                            </a>
                            <a class="navbar-item" href="{% url 'orders' %}">
                                Orders
                            </a>
                            <a class="navbar-item" href="{% url 'logout' %}">
                                Log out
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <a class="navbar-item" href="{% url 'create_user' %}">
                        Create Account
                    </a>
                    {% endif %}
                </div>
```

2020-08-28 00:55 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +    <!-- {% include "utils/button.html" with button=view.invoices_button %} -->
I believe there was some discussion about moving it to the profile screen we have yet to delete. I left it commented because it's not available anywhere else and I'm still getting used to this stack and am terrified of loosing the links to things.

2020-08-28 01:51 UTC, blueridger requested changes

2020-08-28 01:51 UTC, blueridger commented on hifireg/registration/templates/registration/base.html
> +                                <a class="navbar-item" href="{% url 'send_email' %}">
wrong url

2020-08-28 01:51 UTC, blueridger commented on hifireg/registration/templates/registration/index.html
> +    <!-- {% include "utils/button.html" with button=view.invoices_button %} -->
keep invoices button on landing page

2020-09-02 01:08 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +    <!-- {% include "utils/button.html" with button=view.invoices_button %} -->
Done

2020-09-02 01:12 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> -<div class="field">
Done

2020-09-02 01:12 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +{% include "utils/form_fields.html" %}
Done

2020-09-02 01:14 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +    {% include "utils/button.html" with button=view.register_button %}
Done

2020-09-02 01:15 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> -<div class="field">
Maybe not....

2020-09-02 01:15 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +{% include "utils/form_fields.html" %}
Maybe not....

2020-09-02 01:19 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +<p>We look forward to dancing with you at this year's HiFi Fusion!</p>
I think done?

2020-09-02 01:21 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> +                {% endif %}
Done

2020-09-02 01:34 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> +                                <a class="navbar-item" href="{% url 'send_email' %}">
I can't change it to 'Account' because that page doesn't exist yet and it will crash the site.

2020-09-02 04:22 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +    {% include "utils/button.html" with button=view.register_button %}
done

2020-09-02 04:22 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +{% include "utils/form_fields.html" %}
done

2020-09-02 04:22 UTC, AshlandWest commented on hifireg/registration/templates/registration/index.html
> +<p>We look forward to dancing with you at this year's HiFi Fusion!</p>
done

2020-09-02 04:27 UTC, AshlandWest commented on hifireg/registration/templates/registration/base.html
> +                                <a class="navbar-item" href="{% url 'send_email' %}">
Done

2020-09-02 04:51 UTC, bryant-ferguson approved these changes

2020-09-02 04:51 UTC, bferg88 commented on hifireg/registration/templates/registration/register_donate.html
> +  <div class="field {{field_classes}}">
delete `{{field_classes}}`

2020-09-02 04:53 UTC, bferg88 commented
Just squash and you're good.

2020-09-02 05:14 UTC, AshlandWest commented
All comments resolved.

2020-09-02 05:15 UTC, merged