Added | Dynamic subtotal on selection page
blueridger/HiFi-Registration pull request #35
Opened 2020-09-20 19:01 UTC by tiftaylor

- Quick Fix | added "," to the special_sauce dollars helper for continuity over $999
- Added | new data prop called newTotalInCents in add_remove_item_view on helpers.py
- Added | a new param (used as 2nd param) to add_remove_item_view function from helpers.py. and added the value self.order for it on reg.py
- Added | functionality accessing data.newTotalInCents to ticket_selection.js for all add/remove checkbox and option tags and converted cents to dollars for render
- Added | span tag with ID for access for dynamic subtotal change on register_products.html

2020-09-20 19:58 UTC, bferg88 commented on hifireg/registration/templatetags/special_sauce.py
> +    return f"${value * 0.01:,.2f}"
I just removed this in a recent commit as it breaks the donation page and creates some inconsistency there.

Before putting this back in, let's decide if it's an important aesthetic to maintain. I imagine most representations of currency on the page are unlikely to exceed $999 at any time, so I'm not sure it's worth the extra effort to maintain that aesthetic.

2020-09-20 20:09 UTC, bferg88 requested changes

2020-09-20 20:09 UTC, bferg88 commented on hifireg/registration/static/scripts/ticket_selection.js
> +function dollars(value) {
A similar function exists in "invoices.js" and "checkout.js" -- these should be consolidated, along with this one, perhaps put it in a new file: "helpers.js". 

This is becoming relevant now because inconsistency in the way numbers are formatted may lead to subtle bugs like the one mentioned below. After some consolidation, when we decide on a consistent currency formatting strategy, we will only have to review two functions-- one in python code and once in javascript.

2020-09-20 20:51 UTC, bferg88 commented on hifireg/registration/templatetags/special_sauce.py
> +    return f"${value * 0.01:,.2f}"
For a little more info on this. The problem is that the current regex for the donation input doesn't expect commas and doesn't reformat into commas. The current strategy for that input box is to remove any characters not matching the pattern - so it would have to be reworked a little if we wanted to insert commas into the expression as they type, but simultaneously not destroy a partially entered decimal portion. 

It could be done and would be pretty cool, but it would take some thinking. A simpler strategy would be to standardize on not showing commas and make a task to revisit the formatting functions and the donation box to allow them all to consistently show the commas.

2020-09-20 22:21 UTC, blueridger requested changes

2020-09-20 22:21 UTC, blueridger commented on hifireg/registration/templates/registration/register_products.html
>        <!-- TODO: This is not dynamically populating "Live" when boxes are checked or unchecked (it does if you manually reload) -->
Should be removed

2020-09-20 22:21 UTC, blueridger commented on hifireg/registration/templatetags/special_sauce.py
> +    return f"${value * 0.01:,.2f}"
I agree commas probably aren't very important for our use case.

2020-09-22 00:40 UTC, tiftaylor commented on hifireg/registration/templatetags/special_sauce.py
> +    return f"${value * 0.01:,.2f}"
I have Removed the comma

2020-09-22 00:47 UTC, tiftaylor commented on hifireg/registration/static/scripts/ticket_selection.js
> +function dollars(value) {
A helper file was created

2020-09-22 00:48 UTC, tiftaylor commented on hifireg/registration/templates/registration/register_products.html
>        <!-- TODO: This is not dynamically populating "Live" when boxes are checked or unchecked (it does if you manually reload) -->
This has been removed

2020-09-22 03:38 UTC, bferg88 commented on hifireg/registration/static/scripts/ticket_selection.js
> +function dollars(value) {
Sweet, thanks.

2020-09-22 03:48 UTC, bferg88 approved these changes
Excellent. Looks good to me.

2020-09-22 04:34 UTC, blueridger commented on hifireg/registration/templates/registration/base.html
> +    <script src="{% static "scripts/helpers.js" %}"></script>
How many pages depend on this script? Ideally we would only import this where needed.

2020-09-24 18:27 UTC, tiftaylor commented on hifireg/registration/templates/registration/base.html
> +    <script src="{% static "scripts/helpers.js" %}"></script>
I felt this was the safest place to put this based on how many files there are. Please suggest a different page because I can't quite figure out the best place, if this isn't it. Happy to move the line if you can suggest where. Thanks!

2020-09-24 19:24 UTC, blueridger commented on hifireg/registration/templates/registration/base.html
> +    <script src="{% static "scripts/helpers.js" %}"></script>
Eh its fine I guess.

2020-09-24 22:09 UTC, bferg88 commented on hifireg/registration/templates/registration/base.html
> +    <script src="{% static "scripts/helpers.js" %}"></script>
Is probably fine, but I would say if you want to make sure it's only imported as necessary, import it right before the scripts that depend on it. So, right before anywhere these scripts are sourced:
`invoices.js`
`ticket_selection.js`
`checkout.js`

2020-09-24 23:09 UTC, tiftaylor commented on hifireg/registration/templates/registration/base.html
> +    <script src="{% static "scripts/helpers.js" %}"></script>
I have moved the script tag to 3 pages this helper is used. Please review and approve and merge. Thanks!

2020-09-25 00:46 UTC, blueridger approved these changes

2020-09-25 00:46 UTC, merged